class: "adaptive_mis.models.adaptive.AdaptiveModel"
title: "AdaptUNet"
load_weights: false
params:
  adaptive_layer:
    class: "adaptive_mis.models.adaptive.AdaptiveConv"
    title: "AdaptiveConv"
    params:
      adaptive_kernel_min_size: 3
      adaptive_kernel_max_size: 5
  main_model: !include ./configs/models/unet_3.yaml
